"""
- CLI arguments for source directory, top module, SV files, and log naming.
- Automatic configuration of LD_LIBRARY_PATH and 64-bit mode flags.
- Generates 'run_questa.tcl' using 'vlog' + 'vsim -c' execution.
- Requirements-compliant: '-access +r' removed.
"""

import argparse
import os
import platform
import subprocess
from pathlib import Path

DEFAULT_QUESTASIM_HOME = "/usr/local/tools/mentor/questasim/2023.4/questasim"
# Set by parent scripts (per experiment folder); can be overridden via CLI.
DEFAULT_SRC_DIR = "" 

COMMON_LIB_DIRS = [
    "/usr/lib64", "/usr/lib", "/lib64", "/lib",
    "/usr/local/lib", "/usr/local/lib64",
    "/usr/lib/x86_64-linux-gnu", "/lib/x86_64-linux-gnu",
    "/usr/lib/aarch64-linux-gnu", "/lib/aarch64-linux-gnu",
]

def _arch_dir_flags():
    """Detect architecture and return the appropriate library path and flags."""
    m = platform.machine().lower()
    return ("linux_aarch64", []) if ("aarch64" in m or "arm64" in m) \
           else ("linux_x86_64", ["-64"])

def _ensure_vsim(questa_home: str):
    """Verify that the vsim binary exists."""
    vsim = Path(questa_home) / "bin" / "vsim"
    if not vsim.exists():
        raise SystemExit(f"[ERROR] vsim not found: {vsim}")
    return str(vsim)

def _build_env(questa_home: str):
    """Set up the environment variables required for QuestaSim execution."""
    env = os.environ.copy()
    env["QUESTASIM_HOME"] = questa_home
    arch_dir, _ = _arch_dir_flags()
    
    # Construct LD_LIBRARY_PATH
    ld_parts = [str(Path(questa_home) / arch_dir)]
    for d in COMMON_LIB_DIRS:
        if Path(d).is_dir():
            ld_parts.append(d)
    if env.get("LD_LIBRARY_PATH"):
        ld_parts.append(env["LD_LIBRARY_PATH"])
    env["LD_LIBRARY_PATH"] = ":".join(ld_parts)
    
    # Force 64-bit mode if on x86_64
    if arch_dir == "linux_x86_64":
        env["MTI_VCO_MODE"] = "64"
        env["MGLS_FORCE_VCO_64"] = "1"
    return env

def write_tcl(src_dir: Path, work_dir: Path, log_dir: Path, top: str, files: list, tcl_path: Path):
    """Generate the TCL script used to drive the simulation."""
    log_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by sim.py",
        "onerror {quit -code 1}",
        "onbreak {quit -code 1}",

        f"set SRC_DIR \"{src_dir}\"",
        f"set WORK_DIR \"{work_dir}\"",
        f"set LOG_DIR \"{log_dir}\"",
        f"set TOP \"{top}\"",

        "file mkdir $WORK_DIR",
        "file mkdir $LOG_DIR",
        "transcript file [file join $LOG_DIR \"transcript.log\"]",

        "quietly catch { vmap -del work }",
        "if {[file exists $WORK_DIR]} { file delete -force $WORK_DIR }",
        "if {[catch {vlib $WORK_DIR} err]} { puts $err; quit -code 1 }",
        "if {[catch {vmap work $WORK_DIR} err]} { puts $err; quit -code 1 }",

        "# compile phase",
    ]
    for f in files:
        lines += [
            f"if {{[catch {{vlog -lint \"$SRC_DIR/{f}\"}} err]}} {{",
            "  puts $err",
            "  quit -code 1",
            "}"
        ]

    lines += [
        "# simulation phase",
        "set MAXTIME 100us",  # Adjust as needed
        "if {[catch {",
        "  vsim -c -onfinish exit work.$TOP -do {",
        "    onerror {quit -code 1}",
        "    onbreak {quit -code 1}",
        "    run $MAXTIME",
        "    quit -code 90",   # Exit code 90 indicates timeout
        "  }",
        "} err]} {",
        "  puts $err",
        "  quit -code 1",
        "}",
        "quit -f",
    ]
    tcl_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[INFO] TCL generated: {tcl_path}")

def main():
    ap = argparse.ArgumentParser(description="QuestaSim runner (arg-based)")
    ap.add_argument("--src-dir", default=DEFAULT_SRC_DIR, help="Source directory containing .sv files")
    ap.add_argument("--top", required=True, help="Top module name (e.g., top2)")
    ap.add_argument("--aes", required=True, help="AES design filename (e.g., aes2_1.sv)")
    ap.add_argument("--tb", required=True, help="Testbench filename (e.g., test2_1.sv)")
    ap.add_argument("--questa-home", default=os.environ.get("QUESTASIM_HOME", DEFAULT_QUESTASIM_HOME), 
                    help="Path to QuestaSim installation")
    ap.add_argument("--log-file", default="", help="Path to save a copy of transcript.log (e.g., logs/transcript_1.log)")
    args = ap.parse_args()

    src_dir = Path(args.src_dir).resolve()
    if not src_dir.exists():
        raise SystemExit(f"[ERROR] src-dir does not exist: {src_dir}")

    work_dir = src_dir / "work"
    log_dir  = src_dir / "logs"
    tcl_path = src_dir / "run_questa.tcl"

    questa_home = args.questa_home
    vsim = _ensure_vsim(questa_home)
    env  = _build_env(questa_home)
    _, flags = _arch_dir_flags()

    files = [args.aes, args.tb]
    write_tcl(src_dir, work_dir, log_dir, args.top, files, tcl_path)

    cmd = [vsim] + flags + [
        "-c",
        "-do",
        f'onerror {{quit -code 1}}; onbreak {{quit -code 1}}; source "{str(tcl_path)}"; quit -f'
    ]
    
    # Run simulation with a 120s timeout to prevent zombie processes
    rc = subprocess.run(
        cmd,
        cwd=str(src_dir),
        env=env,
        text=True,
        stdin=subprocess.DEVNULL,   # Disable interactive input
        timeout=120                 
    ).returncode

    if rc != 0:
        print(f"[ERROR] vsim exited with code {rc}")
    else:
        print("[PASS] vsim finished successfully.")

    # Copy the default transcript.log to the user-specified destination
    if args.log_file:
        try:
            src_log = log_dir / "transcript.log"
            dst_log = Path(args.log_file)
            dst_log.parent.mkdir(parents=True, exist_ok=True)
            if src_log.exists():
                dst_log.write_text(src_log.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")
                print(f"[INFO] Saved transcript to {dst_log}")
            else:
                print(f"[WARN] transcript.log not found: {src_log}")
        except Exception as e:
            print(f"[WARN] Failed to save transcript: {e}")

    # Pass through the vsim exit code
    raise SystemExit(rc)

if __name__ == "__main__":
    main()