import os
import platform
import subprocess
from pathlib import Path

# ---- Configuration ----
QUESTASIM_HOME = "/usr/local/tools/mentor/questasim/2023.4/questasim"
SRC_DIR        = "/nas/.../aesv"
WORK_DIR       = Path(SRC_DIR) / "work"
LOG_DIR        = Path(SRC_DIR) / "logs"
TCL_PATH       = Path(SRC_DIR) / "run_questa.tcl"

TOP = "top"
FILES = ["aes.sv", "test.sv"]  # Relative paths to SRC_DIR

COMMON_LIB_DIRS = [
    "/usr/lib64", "/usr/lib", "/lib64", "/lib",
    "/usr/local/lib", "/usr/local/lib64",
    "/usr/lib/x86_64-linux-gnu", "/lib/x86_64-linux-gnu",
    "/usr/lib/aarch64-linux-gnu", "/lib/aarch64-linux-gnu",
]

def _arch_dir_flags():
    m = platform.machine().lower()
    return ("linux_aarch64", []) if ("aarch64" in m or "arm64" in m) \
           else ("linux_x86_64", ["-64"])

def _ensure_vsim():
    vsim = Path(QUESTASIM_HOME) / "bin" / "vsim"
    if not vsim.exists():
        raise SystemExit(f"[ERROR] vsim not found: {vsim}")
    return str(vsim)

def _build_env():
    env = os.environ.copy()
    env["QUESTASIM_HOME"] = QUESTASIM_HOME

    arch_dir, _ = _arch_dir_flags()
    ld_parts = [str(Path(QUESTASIM_HOME) / arch_dir)]
    ld_parts.extend([d for d in COMMON_LIB_DIRS if Path(d).is_dir()])
    if env.get("LD_LIBRARY_PATH"):
        ld_parts.append(env["LD_LIBRARY_PATH"])
    env["LD_LIBRARY_PATH"] = ":".join(ld_parts)

    if arch_dir == "linux_x86_64":
        env["MTI_VCO_MODE"] = "64"
        env["MGLS_FORCE_VCO_64"] = "1"
    return env

def _write_tcl():
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Auto-generated by sim.py",
        f"set SRC_DIR \"{SRC_DIR}\"",
        f"set WORK_DIR \"{WORK_DIR}\"",
        f"set LOG_DIR \"{LOG_DIR}\"",
        f"set TOP \"{TOP}\"",
        "file mkdir $WORK_DIR",
        "file mkdir $LOG_DIR",
        "transcript file [file join $LOG_DIR \"transcript.log\"]",
        "catch { vdel -lib work -all }",
        "vlib $WORK_DIR",
        "vmap work $WORK_DIR",
        "# compile",
        *[f"vlog -lint \"$SRC_DIR/{f}\"" for f in FILES],
        "# simulate",
        # Critical fix: remove '-access +r'
        "vsim -c work.$TOP -do {",
        "  onerror {quit -code 1}",
        "  run -all",
        "  quit -f",
        "}",
    ]
    TCL_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"[INFO] TCL: {TCL_PATH}")

def run():
    _write_tcl()
    vsim = _ensure_vsim()
    env  = _build_env()
    _, flags = _arch_dir_flags()
    cmd = [vsim] + flags + ["-c", "-do", str(TCL_PATH)]
    print(">>", " ".join(cmd))
    rc = subprocess.run(cmd, cwd=SRC_DIR, env=env, text=True).returncode
    if rc != 0:
        raise SystemExit(f"[ERROR] vsim exited with code {rc}")
    print(f"[PASS] Done. Log: {LOG_DIR / 'transcript.log'}")

if __name__ == "__main__":
    run()
